xxx: workaround Werror=deprecated-declarations failure
```
/usr/bin/ccache /usr/bin/g++
-DBOOST_ASIO_DISABLE_THREAD_KEYWORD_EXTENSION -DBOOST_ASIO_HAS
_IO_URING -DBOOST_ASIO_NO_TS_EXECUTORS
-DBOOST_MPL_CFG_NO_PREPROCESSED_HEADERS -DBOOST_MPL_
LIMIT_LIST_SIZE=30 -DHAVE_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE
-D_REENTRANT -D_THR
EAD_SAFE -D__CEPH__ -D__STDC_FORMAT_MACROS -D__linux__
-I/ceph/build/src/include -I/ceph/sr
c -I/ceph/build/src -I/ceph/src/dmclock/src
-I/ceph/src/dmclock/support/src -isystem /ceph/
build/boost/include -isystem /ceph/build/include -isystem
/ceph/src/jaegertracing/opentelem
etry-cpp/api/include -isystem
/ceph/src/jaegertracing/opentelemetry-cpp/exporters/jaeger/in
clude -isystem /ceph/src/jaegertracing/opentelemetry-cpp/ext/include
-isystem /ceph/src/jae
gertracing/opentelemetry-cpp/sdk/include -isystem /ceph/src/xxHash
-isystem /ceph/src/fmt/include -isystem /ceph/src/rocksdb/include
-isystem /ceph/build/src/liburing/src/include -isystem /usr/include/fuse
-Og -Werror -std=c++20 -fPIE -fno-builtin-malloc -fno-builtin-calloc
-fno-builtin-realloc -fno-builtin-free -Wall -fno-strict-aliasing
-fsigned-char -Wtype-limits -Wignored-qualifiers -Wpointer-arith
-Werror=format-security -Winit-self -Wno-unknown-pragmas
-Wnon-virtual-dtor -Wno-ignored-qualifiers -ftemplate-depth-1024
-Wpessimizing-move -Wredundant-move -Wstrict-null-sentinel
-Woverloaded-virtual -DCEPH_DEBUG_MUTEX -fstack-protector-strong
-D_GLIBCXX_ASSERTIONS -fdiagnostics-color=auto -MD -MT
src/CMakeFiles/ceph-osd.dir/osd/objclass.cc.o -MF
src/CMakeFiles/ceph-osd.dir/osd/objclass.cc.o.d -o
src/CMakeFiles/ceph-osd.dir/osd/objclass.cc.o -c
/ceph/src/osd/objclass.cc
In file included from ../src/osd/PrimaryLogPG.h:23,
                 from ../src/osd/objclass.cc:12:
../src/osd/OSD.h: In member function 'void OSD::set_osdmap(OSDMapRef)':
../src/osd/OSD.h:1675:22: error: 'void
std::atomic_store(shared_ptr<_Tp>*, shared_ptr<_Tp>) [with _Tp = const
OSDMap]' is deprecated: use 'std::atomic<std::shared_ptr<T>>' instead
[-Werror=deprecated-declarations]
 1675 |     std::atomic_store(&_osdmap, osdmap);
      |     ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/14/memory:81,
                 from ../src/common/ceph_context.h:20,
                 from ../src/osd/objclass.cc:6:
/usr/include/c++/14/bits/shared_ptr_atomic.h:183:5: note: declared here
  183 |     atomic_store(shared_ptr<_Tp>* __p, shared_ptr<_Tp> __r)
      |     ^~~~~~~~~~~~
../src/osd/OSD.h: In member function 'OSDMapRef OSD::get_osdmap()
const':
../src/osd/OSD.h:1678:28: error: 'std::shared_ptr<_Tp>
std::atomic_load(const shared_ptr<_Tp>*) [with _Tp = const OSDMap]' is
deprecated: use 'std::atomic<std::shared_ptr<T>>' instead
[-Werror=deprecated-declarations]
 1678 |     return std::atomic_load(&_osdmap);
      |            ~~~~~~~~~~~~~~~~^~~~~~~~~~
/usr/include/c++/14/bits/shared_ptr_atomic.h:142:5: note: declared here
  142 |     atomic_load(const shared_ptr<_Tp>* __p)
      |     ^~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

Signed-off-by: John Mulligan <jmulligan@redhat.com>